bump up sync, quote and tokio-postgres to 0.6
Dowwie/tokio-postgres-mapper pull request #11
Opened 2020-12-15 23:18 UTC by DominicWrege

It compiles with tokio-postgres 0.6. Later we have to update tokio-pg-mapper to tokio-postgres 0.6.

2020-12-18 15:17 UTC, Dowwie approved these changes
can you update pg mapper's tokio_postgres dependency?

2020-12-18 15:31 UTC, Dowwie requested changes
can you also update tokio_pg_mapper's tokio_postgres dependency?

2020-12-18 15:59 UTC, DominicWrege commented
sure! :)

2020-12-18 16:04 UTC, Dowwie approved these changes

2020-12-18 16:11 UTC, Dowwie commented
fyi -- if you happen to be using actix-web, these updates won't work until actix-web upgrades to the latest tokio version.  It's still on 0.2.6.

2020-12-18 16:17 UTC, DominicWrege commented
thx

2020-12-26 10:33 UTC, DominicWrege commented
I pushed another commit since tokio v1.0 is out.

2020-12-28 19:53 UTC, Fedott commented on pg_mapper_derive/CHANGELOG.md
> +- bump up sync, quote and tokio-postgres to 0.6
```suggestion
- bump up sync, quote and tokio-postgres to 0.7
```
Misstype

2020-12-30 19:43 UTC, merged